[package]
name = "first-tool-start"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.33.3"
egui = "0.33.3"
sysinfo = "0.38.1"
[target.'cfg(windows)'.dependencies]
windows = { version = "0.62.2", features = [ "Win32_Foundation", "Win32_UI_WindowsAndMessaging",] }